package com.nexauren.imagetools.ui

import android.content.Context

enum class AppLanguage(val code: String, val label: String) {
    PT("pt", "Português"),
    EN("en", "English"),
    ES("es", "Español"),
    FR("fr", "Français")
}

object AppLanguageStore {
    private const val PREFS = "image_tools_preferences"
    private const val KEY_LANGUAGE = "language"

    fun get(context: Context): AppLanguage {
        val code = context.getSharedPreferences(PREFS, Context.MODE_PRIVATE)
            .getString(KEY_LANGUAGE, AppLanguage.PT.code)
        return AppLanguage.entries.firstOrNull { it.code == code } ?: AppLanguage.PT
    }

    fun save(context: Context, language: AppLanguage) {
        context.getSharedPreferences(PREFS, Context.MODE_PRIVATE)
            .edit()
            .putString(KEY_LANGUAGE, language.code)
            .apply()
    }
}

class UiText(private val language: AppLanguage) {
    private val map = when (language) {
        AppLanguage.PT -> pt
        AppLanguage.EN -> en
        AppLanguage.ES -> es
        AppLanguage.FR -> fr
    }

    fun get(key: String): String = map[key] ?: en[key] ?: key

    fun toolTitle(id: String): String = get("tool.$id.title")
    fun toolSubtitle(id: String): String = get("tool.$id.subtitle")
    fun filterTitle(id: String): String = get("filter.$id")

    companion object {
        val pt = mapOf(
            "home" to "Ferramentas de imagem",
            "home.subtitle" to "Entrada • Configurar • Ação • Preview • Exportar",
            "tools" to "Todas as ferramentas",
            "batch" to "Processamento em lote",
            "premium" to "Premium",
            "account" to "Conta",
            "settings" to "Definições",
            "about" to "Sobre",
            "language" to "Idioma",
            "language.help" to "A interface é traduzida imediatamente.",
            "search" to "Pesquisar ferramentas…",
            "popular" to "Mais usadas",
            "all.tools" to "Biblioteca completa",
            "choose.image" to "Selecionar imagem",
            "choose.images" to "Selecionar imagens",
            "choose.another" to "Escolher outra",
            "config" to "2. Configurar",
            "action" to "3. Executar",
            "preview" to "4. Preview do resultado",
            "export" to "5. Exportar",
            "preview.button" to "Gerar preview",
            "processing" to "Processando…",
            "working" to "A trabalhar…",
            "ready" to "Resultado pronto",
            "save" to "Guardar",
            "save.all" to "Guardar tudo",
            "share" to "Partilhar",
            "open" to "Abrir",
            "back" to "Voltar",
            "cancel" to "Cancelar",
            "close" to "Fechar",
            "reset" to "Repor",
            "local" to "Processamento local",
            "private" to "As ferramentas principais processam no dispositivo.",
            "pro" to "PRO",
            "free" to "GRÁTIS",
            "premium.tool" to "Ferramenta Premium",
            "account.login" to "Iniciar sessão para continuar.",
            "paypal" to "Continuar com PayPal",
            "saved" to "Guardado com sucesso.",
            "save.error" to "Não foi possível guardar o resultado.",
            "select.first" to "Selecione uma imagem primeiro.",
            "no.result" to "Gere um preview antes de exportar.",
            "width" to "Largura",
            "height" to "Altura",
            "quality" to "Qualidade",
            "format" to "Formato",
            "aspect" to "Manter proporção",
            "text" to "Texto",
            "opacity" to "Opacidade",
            "position" to "Posição",
            "strength" to "Intensidade",
            "ratio" to "Proporção",
            "angle" to "Ângulo",
            "mirror.h" to "Espelho H",
            "mirror.v" to "Espelho V",
            "batch.select" to "Selecione várias imagens e aplique a mesma operação.",
            "batch.operation" to "Operação em lote",
            "batch.resize" to "Redimensionar todas",
            "batch.compress" to "Comprimir todas",
            "batch.convert" to "Converter todas",
            "batch.filter" to "Aplicar filtro a todas",
            "batch.watermark" to "Marca de água em todas",
            "batch.start" to "Processar lote",
            "batch.ready" to "Lote preparado para exportação.",
            "ocr.title" to "Texto reconhecido",
            "ocr.copy" to "Copiar texto",
            "ocr.empty" to "Não foi encontrado texto legível.",
            "background.remove" to "Remover fundo",
            "background.help" to "Remove o fundo usando segmentação local do dispositivo.",
            "exif.title" to "Dados EXIF",
            "exif.remove" to "Remover EXIF ao reexportar",
            "pdf.create" to "Criar PDF",
            "pdf.ready" to "PDF preparado para guardar.",
            "palette.title" to "Paleta dominante",
            "palette.extract" to "Extrair cores",
            "collage.title" to "Colagem",
            "collage.help" to "Combine 2 a 4 imagens numa grelha.",
            "settings.output" to "Pasta de saída",
            "settings.dark" to "Modo escuro",
            "settings.legal" to "Privacidade, termos e suporte",
            "about.text" to "Ferramentas rápidas para edição, conversão e organização de imagens.",
            "signout" to "Terminar sessão",
            "tool.resize.title" to "Redimensionar",
            "tool.resize.subtitle" to "Dimensões exatas com proporção",
            "tool.compress.title" to "Comprimir",
            "tool.compress.subtitle" to "Reduzir tamanho com controlo",
            "tool.convert.title" to "Converter",
            "tool.convert.subtitle" to "JPEG, PNG e WEBP",
            "tool.crop.title" to "Cortar",
            "tool.crop.subtitle" to "Proporções para redes e web",
            "tool.rotate.title" to "Rodar e espelhar",
            "tool.rotate.subtitle" to "Corrigir orientação",
            "tool.filter.title" to "Filtros",
            "tool.filter.subtitle" to "Presets rápidos",
            "tool.watermark.title" to "Marca de água",
            "tool.watermark.subtitle" to "Adicionar texto à imagem",
            "tool.details.title" to "Detalhes",
            "tool.details.subtitle" to "Dimensões, formato e tamanho",
            "tool.brightness.title" to "Brilho",
            "tool.brightness.subtitle" to "Clarear ou escurecer",
            "tool.contrast.title" to "Contraste",
            "tool.contrast.subtitle" to "Mais ou menos contraste",
            "tool.saturation.title" to "Saturação",
            "tool.saturation.subtitle" to "Aumentar ou reduzir cor",
            "tool.warmth.title" to "Temperatura",
            "tool.warmth.subtitle" to "Ajuste frio ↔ quente",
            "tool.negative.title" to "Negativo",
            "tool.negative.subtitle" to "Inverter cores",
            "tool.blur.title" to "Desfocar",
            "tool.blur.subtitle" to "Desfoque rápido",
            "tool.sharpen.title" to "Nitidez",
            "tool.sharpen.subtitle" to "Realçar detalhes",
            "tool.pixelate.title" to "Pixelizar",
            "tool.pixelate.subtitle" to "Blocos para efeito ou privacidade",
            "tool.border.title" to "Moldura",
            "tool.border.subtitle" to "Adicionar margem",
            "tool.round.title" to "Cantos arredondados",
            "tool.round.subtitle" to "Dar acabamento aos cantos",
            "tool.metadata.title" to "Limpar metadados",
            "tool.metadata.subtitle" to "Remover metadados ao reexportar",
            "tool.pdf.title" to "Imagem → PDF",
            "tool.pdf.subtitle" to "Criar um PDF a partir da imagem",
            "tool.palette.title" to "Paleta de cores",
            "tool.palette.subtitle" to "Extrair cinco cores dominantes",
            "tool.collage.title" to "Colagem rápida",
            "tool.collage.subtitle" to "Combinar 2–4 imagens",
            "tool.ocr.title" to "OCR",
            "tool.ocr.subtitle" to "Extrair texto da imagem",
            "tool.background.title" to "Remover fundo",
            "tool.background.subtitle" to "Recortar o assunto principal",
            "tool.exif.title" to "EXIF",
            "tool.exif.subtitle" to "Ler e limpar dados da fotografia"
        )
        val en = pt + mapOf(
            "home" to "Image tools",
            "home.subtitle" to "Input • Configure • Action • Preview • Export",
            "tools" to "All tools",
            "batch" to "Batch processing",
            "premium" to "Premium",
            "account" to "Account",
            "settings" to "Settings",
            "about" to "About",
            "language" to "Language",
            "search" to "Search tools…",
            "popular" to "Popular",
            "all.tools" to "Complete library",
            "choose.image" to "Select image",
            "choose.images" to "Select images",
            "choose.another" to "Choose another",
            "config" to "2. Configure",
            "action" to "3. Action",
            "preview" to "4. Result preview",
            "export" to "5. Export",
            "preview.button" to "Generate preview",
            "processing" to "Processing…",
            "working" to "Working…",
            "ready" to "Result ready",
            "save" to "Save",
            "save.all" to "Save all",
            "share" to "Share",
            "back" to "Back",
            "language.help" to "The interface changes immediately.",
            "batch.select" to "Select multiple images and apply the same operation.",
            "batch.operation" to "Batch operation",
            "batch.resize" to "Resize all",
            "batch.compress" to "Compress all",
            "batch.convert" to "Convert all",
            "batch.filter" to "Filter all",
            "batch.watermark" to "Watermark all",
            "batch.start" to "Process batch",
            "batch.ready" to "Batch ready to export.",
            "ocr.title" to "Recognized text",
            "ocr.copy" to "Copy text",
            "ocr.empty" to "No readable text found.",
            "background.remove" to "Remove background",
            "background.help" to "Remove the background using on-device segmentation.",
            "exif.title" to "EXIF data",
            "exif.remove" to "Remove EXIF on export",
            "pdf.create" to "Create PDF",
            "pdf.ready" to "PDF ready to save.",
            "palette.title" to "Dominant palette",
            "palette.extract" to "Extract colors",
            "collage.title" to "Collage",
            "collage.help" to "Combine 2 to 4 images into a grid.",
            "settings.output" to "Output folder",
            "settings.dark" to "Dark mode",
            "settings.legal" to "Privacy, terms and support",
            "about.text" to "Fast tools for editing, conversion and image organization.",
            "signout" to "Sign out",
            "tool.resize.title" to "Resize",
            "tool.resize.subtitle" to "Exact dimensions with aspect ratio",
            "tool.compress.title" to "Compress",
            "tool.compress.subtitle" to "Reduce size with control",
            "tool.convert.title" to "Convert",
            "tool.convert.subtitle" to "JPEG, PNG and WEBP",
            "tool.crop.title" to "Crop",
            "tool.crop.subtitle" to "Ratios for social and web",
            "tool.rotate.title" to "Rotate & flip",
            "tool.rotate.subtitle" to "Correct orientation",
            "tool.filter.title" to "Filters",
            "tool.filter.subtitle" to "Quick presets",
            "tool.watermark.title" to "Watermark",
            "tool.watermark.subtitle" to "Add text to the image",
            "tool.details.title" to "Details",
            "tool.details.subtitle" to "Dimensions, format and size",
            "tool.brightness.title" to "Brightness",
            "tool.brightness.subtitle" to "Lighten or darken",
            "tool.contrast.title" to "Contrast",
            "tool.contrast.subtitle" to "Increase or soften",
            "tool.saturation.title" to "Saturation",
            "tool.saturation.subtitle" to "Boost or mute color",
            "tool.warmth.title" to "Warmth",
            "tool.warmth.subtitle" to "Cool ↔ warm control",
            "tool.negative.title" to "Negative",
            "tool.negative.subtitle" to "Invert colors",
            "tool.blur.title" to "Blur",
            "tool.blur.subtitle" to "Quick blur",
            "tool.sharpen.title" to "Sharpen",
            "tool.sharpen.subtitle" to "Bring out detail",
            "tool.pixelate.title" to "Pixelate",
            "tool.pixelate.subtitle" to "Blocks for effect or privacy",
            "tool.border.title" to "Border",
            "tool.border.subtitle" to "Add clean margins",
            "tool.round.title" to "Rounded corners",
            "tool.round.subtitle" to "Finish the image corners",
            "tool.metadata.title" to "Clean metadata",
            "tool.metadata.subtitle" to "Remove common metadata on export",
            "tool.pdf.title" to "Image → PDF",
            "tool.pdf.subtitle" to "Create PDF from an image",
            "tool.palette.title" to "Color palette",
            "tool.palette.subtitle" to "Extract five dominant colors",
            "tool.collage.title" to "Quick collage",
            "tool.collage.subtitle" to "Combine 2–4 images",
            "tool.ocr.title" to "OCR",
            "tool.ocr.subtitle" to "Extract text from an image",
            "tool.background.title" to "Remove background",
            "tool.background.subtitle" to "Keep the main subject",
            "tool.exif.title" to "EXIF",
            "tool.exif.subtitle" to "Read and clean photo metadata"
        )
        val es = en + mapOf(
            "home" to "Herramientas de imagen", "tools" to "Todas las herramientas", "batch" to "Procesamiento por lotes",
            "premium" to "Premium", "account" to "Cuenta", "settings" to "Ajustes", "about" to "Acerca de",
            "language" to "Idioma", "search" to "Buscar herramientas…", "popular" to "Populares",
            "choose.image" to "Seleccionar imagen", "choose.images" to "Seleccionar imágenes", "choose.another" to "Elegir otra",
            "config" to "2. Configurar", "action" to "3. Ejecutar", "preview" to "4. Vista previa", "export" to "5. Exportar",
            "preview.button" to "Generar vista previa", "processing" to "Procesando…", "save" to "Guardar", "save.all" to "Guardar todo",
            "share" to "Compartir", "back" to "Volver", "open" to "Abrir", "signout" to "Cerrar sesión",
            "batch.select" to "Selecciona varias imágenes y aplica la misma operación.",
            "batch.operation" to "Operación por lotes", "batch.resize" to "Redimensionar todas",
            "batch.compress" to "Comprimir todas", "batch.convert" to "Convertir todas", "batch.filter" to "Aplicar filtro a todas",
            "batch.watermark" to "Marca de agua en todas", "batch.start" to "Procesar lote", "batch.ready" to "Lote listo para exportar.",
            "ocr.title" to "Texto reconocido", "ocr.copy" to "Copiar texto", "ocr.empty" to "No se encontró texto legible.",
            "background.remove" to "Eliminar fondo", "background.help" to "Elimina el fondo mediante segmentación local.",
            "exif.title" to "Datos EXIF", "exif.remove" to "Eliminar EXIF al exportar",
            "pdf.create" to "Crear PDF", "pdf.ready" to "PDF listo para guardar.", "palette.title" to "Paleta dominante",
            "palette.extract" to "Extraer colores", "collage.title" to "Collage", "collage.help" to "Combina de 2 a 4 imágenes en una cuadrícula.",
            "settings.output" to "Carpeta de salida", "settings.dark" to "Modo oscuro", "settings.legal" to "Privacidad, términos y soporte",
            "about.text" to "Herramientas rápidas para editar, convertir y organizar imágenes."
        )
        val fr = en + mapOf(
            "home" to "Outils d’image", "tools" to "Tous les outils", "batch" to "Traitement par lots",
            "premium" to "Premium", "account" to "Compte", "settings" to "Réglages", "about" to "À propos",
            "language" to "Langue", "search" to "Rechercher des outils…", "popular" to "Populaires",
            "choose.image" to "Sélectionner une image", "choose.images" to "Sélectionner des images", "choose.another" to "Choisir une autre",
            "config" to "2. Configurer", "action" to "3. Action", "preview" to "4. Aperçu du résultat", "export" to "5. Exporter",
            "preview.button" to "Générer l’aperçu", "processing" to "Traitement…", "save" to "Enregistrer", "save.all" to "Tout enregistrer",
            "share" to "Partager", "back" to "Retour", "open" to "Ouvrir", "signout" to "Se déconnecter",
            "batch.select" to "Sélectionnez plusieurs images et appliquez la même opération.",
            "batch.operation" to "Opération par lots", "batch.resize" to "Redimensionner tout",
            "batch.compress" to "Compresser tout", "batch.convert" to "Convertir tout", "batch.filter" to "Appliquer le filtre",
            "batch.watermark" to "Filigrane sur tout", "batch.start" to "Traiter le lot", "batch.ready" to "Lot prêt à être exporté.",
            "ocr.title" to "Texte reconnu", "ocr.copy" to "Copier le texte", "ocr.empty" to "Aucun texte lisible trouvé.",
            "background.remove" to "Supprimer l’arrière-plan", "background.help" to "Supprime l’arrière-plan avec une segmentation locale.",
            "exif.title" to "Données EXIF", "exif.remove" to "Supprimer EXIF à l’export",
            "pdf.create" to "Créer un PDF", "pdf.ready" to "PDF prêt à être enregistré.", "palette.title" to "Palette dominante",
            "palette.extract" to "Extraire les couleurs", "collage.title" to "Collage", "collage.help" to "Combinez 2 à 4 images dans une grille.",
            "settings.output" to "Dossier de sortie", "settings.dark" to "Mode sombre", "settings.legal" to "Confidentialité, conditions et support",
            "about.text" to "Des outils rapides pour modifier, convertir et organiser les images."
        )
    }
}
